services:
  main-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=egormartynenko
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=postgres
    volumes:
      - main-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U egormartynenko -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  main-db: